### ISSUE TITLE
CSS 기본 구조 세팅 및 모바일 UI 스타일링

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/deal-3#12]
## 개요 

컬러 값들을 SCSS 변수에 설정하고 모바일 크기로 UI 세팅을 완료합니다.

## 소요 시간 

1h

## 진행 사항 

- [x] css 기본 구조 세팅
- [x] 모바일 UI 스타일링

**Comment by Seogeurim** [comment]
소요시간 : 1시간 30분
