### ISSUE TITLE
TextInput 컴포넌트 구현

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/deal-3#16]
## 개요 

박스 모양 Input 컴포넌트인 TextInput 컴포넌트를 구현합니다.

## 소요 시간 

2h

## 진행 사항 

- [x] TextInput 컴포넌트 레이아웃 구현
- [x] initial / active / typing / filled 상태에 따라 스타일 달리 구현

**Comment by Seogeurim** [comment]
소요 시간 : 40분
