### ISSUE TITLE
프론트엔드 SPA 구조 개선

### ISSUE THREAD

**Issue by Seogeurim** [woowa-techcamp-2021/deal-3#20]
## 개요 

프론트엔드 SPA 구조를 개선합니다. 특히 렌더링 최적화에 초점을 맞추고 진행합니다.

## 소요 시간 

4h

## 진행 사항 

- [x] 렌더링 최적화
- [x] PropsType & StateType 기본 타입 정의
- [x] props로 function 넘겨줄 때 this bind
- [x] 이벤트 핸들러 추가하는 방식 개선
- [x] 컴포넌트에 자식 추가하는 방식 개선
- [x] 기존 컴포넌트에 개선된 컴포넌트 구조 반영
- [x] 라우터 컴포넌트에 개선된 컴포넌트 구조 반영

**Comment by Seogeurim** [comment]
PropsType & StateType에 대하여 기본 타입 정의 어떻게 할지 논의 필요

**Comment by Seogeurim** [comment]
소요 시간 : 3h

**Comment by hseoy** [comment]
소요 시간 : 3h + 2h (5h)
