### ISSUE TITLE
Back-End 프로젝트 세팅

### ISSUE THREAD

**Issue by Seogeurim** [woowa-techcamp-2021/deal-3#9]
## 개요 

express 백엔드 프로젝트를 생성하고 설정합니다.

## 진행 사항 

- [x] express 서버 구축
- [x] 서버 코드 모듈화
- [x] nodemon 추가하기
- [x] env-cmd 설정

**Comment by Seogeurim** [comment]
env-cmd 설정이 필요할 것 같습니다. 두 가지 설정 방법이 있을 것 같은데, 

첫번째는 

`.env`, `.env.dev` 이런 식으로 파일을 생성하고 스크립트에 `env-cmd -f .env` 명령어를 추가해주는 것

두번째는

`.env-cmdrc` 파일을 아래와 같이 생성하고 스크립트에 `env-cmd -e development` 명령어를 추가해주는 것

```json
{
  "development": {
    "NODE_ENV": "development",
    "PORT": "8080"
  },
  "production": {
    "NODE_ENV": "production",
    "PORT": "7070"
  }
}
```

입니다. 같이 토의해보고 결정하면 좋을 것 같아요 !! 😆

**Comment by hseoy** [comment]
.env 를 사용하는 쪽이 env-cmd 패키지만을 위한 것이 아니라 더 일반적인 설정인 것 같아서 첫 번째 방식으로 진행하는 것이 좋을 것 같아요.
